---
- name: Include variables
  ansible.builtin.include_tasks: variables.yml

- name: Install ocserv
  become: true
  ansible.builtin.package:
    name: ocserv
    state: present

- name: Configure ocserv
  become: true
  ansible.builtin.template:
    src: ocserv.conf.j2
    dest: /etc/ocserv/ocserv.conf
    owner: root
    group: root
    mode: "0644"
  notify: Reload ocserv

- name: Create script dir
  become: true
  ansible.builtin.file:
    path: /etc/ocserv/scripts
    state: directory
    mode: "0755"

- name: Copy scripts
  become: true
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/ocserv/scripts/{{ item }}"
    owner: root
    group: root
    mode: "0750"
  with_items:
    - connect.sh
    - disconnect.sh
  when: ocserv_use_connect_script or ocserv_use_disconnect_script
  notify: Reload ocserv

- name: Deploy PAM config
  become: true
  ansible.builtin.copy:
    src: etc_pam_d_ocserv
    dest: /etc/pam.d/ocserv
    owner: root
    group: root
    mode: "0644"
  when: ocserv_pam_otp
