---
  - include_tasks: variables.yml

  - name: Install ocserv
    become: True
    apt:
      name: ocserv
      state: present
      update_cache: True
      cache_valid_time: 1800

  - name: Configure ocserv
    become: True
    template:
      src: ocserv.conf.j2
      dest: /etc/ocserv/ocserv.conf
      owner: root
      group: root
      mode: 0644
    notify: reload-ocserv

  - name: Create script dir
    become: True
    file:
      path: /etc/ocserv/scripts
      state: directory

  - name: Copy scripts
    become: True
    template:
      src: "{{ item }}.j2"
      dest: "/etc/ocserv/scripts/{{ item }}"
      owner: root
      group: root
      mode: 0750
    with_items:
      - connect.sh
      - disconnect.sh
    when: ocserv_use_connect_script or ocserv_use_disconnect_script
    notify: reload-ocserv

  - name: Deploy PAM config
    become: True
    copy:
      src: etc_pam_d_ocserv
      dest: /etc/pam.d/ocserv
      owner: root
      group: root
      mode: 0644
