---
  - name: Install ocserv
    become: True
    apt:
      name: ocserv
      state: present
      update_cache: True
      cache_valid_time: 1800

  - name: Configure ocserv
    become: True
    template:
      src: ocserv.conf.j2
      dest: /etc/ocserv/ocserv.conf
      owner: root
      group: root
      mode: 0644
    notify: reload-ocserv

  - name: Kill systemd socket
    become: True
    systemd:
      name: ocserv.socket
      masked: True

  - name: Overwrite systemd unit file
    become: True
    copy:
      src: ocserv.service
      dest: /etc/systemd/system/ocserv.service
    notify: reload systemd

  - name: Create script dir
    become: True
    file:
      path: /etc/ocserv/scripts
      state: directory

  - name: Copy scripts
    become: True
    template:
      src: "{{ item }}.j2"
      dest: "/etc/ocserv/scripts/{{ item }}"
      owner: root
      group: root
      mode: 0750
    with_items:
      - connect.sh
      - disconnect.sh
    notify: reload-ocserv
