- name: Check oc_default_domain variable
  fail:
    msg: "Bailing out: ocserv_default_domain is not set"
  when: ocserv_default_domain|length == 0

- fail:
    msg: "Bailing out: ocserv_cl_network is not set"
  when: ocserv_cl_network|length == 0

- fail:
    msg: "Bailing out: ocserv_routes is not set"
  when: ocserv_routes|length == 0
