---
  - name: reload-ocserv
    become: True
    service:
      name: ocserv.service
      enabled: True
      state: restarted

  - name: reload systemd
    become: True
    systemd:
      daemon_reload: True
