name: linting

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: lint
        uses: ansible/ansible-lint-action@main
        with:
          targets: "."
